openapi: 3.2.0
info:
  title: Verato Person Household Query API
  version: 2026.1.2
servers:
- url: https://yourveratodomain.com/link-ws/svc
  description: Production Link API
- url: https://yourveratodomain.com/link-ws/svc
  description: Sandbox Link API
security:
- basicAuth: []
tags:
- name: HouseholdQuery
paths:
  /householdQuery:
    post:
      summary: Query for Household (householdQuery)
      description: Used to retrieve the collection of Link IDs that have been grouped into a household.
      operationId: post_householdQuery
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceResponse_householdQuery'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceRequest_householdQuery'
      tags:
      - HouseholdQuery
components:
  schemas:
    HouseholdQueryWsResponse:
      type: object
      properties:
        householdId:
          type: string
          description: The householdId.
        lastUpdateDate:
          type: string
          format: date-time
        linkIdsInHousehold:
          type: array
          items:
            type: string
          uniqueItems: true
          description: Current linkIds in the household.
        createDate:
          type: string
          format: date-time
      required:
      - householdId
      - linkIdsInHousehold
    Source:
      type: object
      properties:
        date:
          type: string
          description: The date of the source data in ISO format (yyyy-mm-dd).
        name:
          type: string
          description: The name of the data source.  Must be unique across Verato.
        id:
          type: string
          description: The ID of an identity within the given data source.
      description: Represents the information tracking an identity to a source that contains the identity
    ServiceRequest_householdQuery:
      type: object
      properties:
        content:
          $ref: '#/components/schemas/HouseholdQueryWsRequest'
        trackingId:
          type: string
    ServiceResponse_householdQuery:
      type: object
      properties:
        auditId:
          type: string
        success:
          type: boolean
        warnings:
          type: array
          items:
            type: string
        retryableError:
          type: boolean
        message:
          type: string
        content:
          $ref: '#/components/schemas/HouseholdQueryWsResponse'
        errors:
          type: array
          items:
            type: string
        trackingId:
          type: string
    HouseholdQueryWsRequest:
      type: object
      properties:
        householdId:
          type: string
          description: The householdId to use in the query
        linkId:
          type: string
          description: The link ID to use in the query
        source:
          $ref: '#/components/schemas/Source'
          description: The SourceNative to use in the query
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
