openapi: 3.2.0
info:
  title: Verato Person Deactivate Source Ws API
  version: 2026.1.2
servers:
- url: https://yourveratodomain.com/link-ws/svc
  description: Production Link API
- url: https://yourveratodomain.com/link-ws/svc
  description: Sandbox Link API
security:
- basicAuth: []
tags:
- name: DeactivateSourceWs
paths:
  /deactivateSourceWs:
    post:
      summary: Deactivate source from identities (deactivateSourceWs)
      description: Used to deactivate (logically delete) a source record from your instance of Universal Identity.
      operationId: post_deactivateSourceWs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceResponse_deactivateSourceWs'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceRequest_deactivateSourceWs'
      tags:
      - DeactivateSourceWs
components:
  schemas:
    Source:
      type: object
      properties:
        date:
          type: string
          description: The date of the source data in ISO format (yyyy-mm-dd).
        name:
          type: string
          description: The name of the data source.  Must be unique across Verato.
        id:
          type: string
          description: The ID of an identity within the given data source.
      description: Represents the information tracking an identity to a source that contains the identity
    DeactivateSourceWsResponse:
      type: object
      properties:
        linkIdsModified:
          type: array
          items:
            type: string
          description: Entity Ids which got modified
        linkIdsDeactivated:
          type: array
          items:
            type: string
          description: Entity Ids which got fully deactivated
      required:
      - linkIdsModified
      - linkIdsDeactivated
      description: Service response for a DeactivateSourceWsResponse
    ServiceResponse_deactivateSourceWs:
      type: object
      properties:
        auditId:
          type: string
        success:
          type: boolean
        warnings:
          type: array
          items:
            type: string
        retryableError:
          type: boolean
        message:
          type: string
        content:
          $ref: '#/components/schemas/DeactivateSourceWsResponse'
        errors:
          type: array
          items:
            type: string
        trackingId:
          type: string
    DeactivateSourceWsRequest:
      type: object
      required:
      - sourceToDeactivate
      properties:
        sourceToDeactivate:
          $ref: '#/components/schemas/Source'
          description: The source to deactivate.
    ServiceRequest_deactivateSourceWs:
      type: object
      properties:
        content:
          $ref: '#/components/schemas/DeactivateSourceWsRequest'
        trackingId:
          type: string
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
