openapi: 3.2.0
info:
  title: Verato Person Reactivate Source Ws API
  version: 2026.1.2
servers:
- url: https://yourveratodomain.com/link-ws/svc
  description: Production Link API
- url: https://yourveratodomain.com/link-ws/svc
  description: Sandbox Link API
security:
- basicAuth: []
tags:
- name: ReactivateSourceWs
paths:
  /reactivateSourceWs:
    post:
      summary: Reactivate source from identities (reactivateSourceWs)
      description: Used to reactivate a source record from your instance of Universal Identity, that was previously deactivated.
      operationId: post_reactivateSourceWs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceResponse_reactivateSourceWs'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceRequest_reactivateSourceWs'
      tags:
      - ReactivateSourceWs
components:
  schemas:
    Source:
      type: object
      properties:
        date:
          type: string
          description: The date of the source data in ISO format (yyyy-mm-dd).
        name:
          type: string
          description: The name of the data source.  Must be unique across Verato.
        id:
          type: string
          description: The ID of an identity within the given data source.
      description: Represents the information tracking an identity to a source that contains the identity
    ReactivateSourceWsRequest:
      type: object
      required:
      - sourceToReactivate
      properties:
        sourceToReactivate:
          $ref: '#/components/schemas/Source'
          description: The source to reactivate.
    ServiceRequest_reactivateSourceWs:
      type: object
      properties:
        content:
          $ref: '#/components/schemas/ReactivateSourceWsRequest'
        trackingId:
          type: string
    ServiceResponse_reactivateSourceWs:
      type: object
      properties:
        auditId:
          type: string
        success:
          type: boolean
        warnings:
          type: array
          items:
            type: string
        retryableError:
          type: boolean
        message:
          type: string
        content:
          $ref: '#/components/schemas/ReactivateSourceWsResponse'
        errors:
          type: array
          items:
            type: string
        trackingId:
          type: string
    ReactivateSourceWsResponse:
      type: object
      properties:
        linkIdsModified:
          type: array
          items:
            type: string
          description: Entity Ids which got modified
        linkIdCreated:
          type: string
          description: Entity Id which got created
      required:
      - linkIdsModified
      description: Service response for a ReactivateSourceWsResponse
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
